name: CI CalculatorAAN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Versión estable actual

      - name: Se configura JDK 21 (Temurin)
        uses: actions/setup-java@v4 # Versión estable actual
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'gradle'

      - name: Asegura que gradlew sea ejecutable
        run: chmod +x ./gradlew

      - name: Compilación
        # Se corrigió el guion largo por doble guion estándar --
        run: ./gradlew compileJava --no-daemon