name: CI CalculatorMRM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Este bloque hace que no tengas que poner working-directory en cada paso
    defaults:
      run:
        working-directory: ./calculatorMRM

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configuración de JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'gradle'

      - name: Asegurar que gradlew sea ejecutable
        # Ahora sí encontrará el archivo porque estamos en la carpeta correcta
        run: chmod +x ./gradlew

      - name: Compilación
        # Usamos --no-daemon para evitar procesos en segundo plano en CI
        run: ./gradlew compileJava --no-daemon